import type { Service } from '@/types/service'

export const services: Service[] = [
  {
    id: 'hair-cut',
    name: 'Hair Cut',
    category: 'Hair',
    description: 'A precision cut tailored to your face shape and lifestyle, finished with a signature blow-dry.',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80',
    durationMinutes: 45,
    startingPrice: 65,
  },
  {
    id: 'hair-coloring',
    name: 'Hair Coloring',
    category: 'Hair',
    description: 'Full-color transformations using premium, low-damage color systems matched to your skin tone.',
    image: 'https://images.unsplash.com/photo-1470259078422-826894b933aa?auto=format&fit=crop&q=80',
    durationMinutes: 120,
    startingPrice: 140,
  },
  {
    id: 'highlights',
    name: 'Highlights',
    category: 'Hair',
    description: 'Hand-painted balayage and foil highlights for dimension that grows out beautifully.',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80',
    durationMinutes: 150,
    startingPrice: 180,
  },
  {
    id: 'keratin-treatment',
    name: 'Keratin Treatment',
    category: 'Hair',
    description: 'A smoothing keratin treatment that reduces frizz and cuts styling time for months.',
    image: 'https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&q=80',
    durationMinutes: 150,
    startingPrice: 220,
  },
  {
    id: 'hair-spa',
    name: 'Hair Spa',
    category: 'Spa',
    description: 'A deeply nourishing scalp and hair ritual with warm oil massage and restorative masks.',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80',
    durationMinutes: 60,
    startingPrice: 85,
  },
  {
    id: 'bridal-makeup',
    name: 'Bridal Makeup',
    category: 'Makeup',
    description: 'A bespoke bridal look with a trial session, long-wear formulas, and on-site touch-ups available.',
    image: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&q=80',
    durationMinutes: 90,
    startingPrice: 250,
  },
  {
    id: 'makeup',
    name: 'Makeup',
    category: 'Makeup',
    description: 'Editorial-quality makeup application for events, photoshoots, or a special night out.',
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?auto=format&fit=crop&q=80',
    durationMinutes: 60,
    startingPrice: 95,
  },
  {
    id: 'facial',
    name: 'Facial',
    category: 'Spa',
    description: 'A customized facial with deep cleansing, exfoliation, and a hydrating mask for radiant skin.',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80',
    durationMinutes: 60,
    startingPrice: 110,
  },
  {
    id: 'nail-care',
    name: 'Nail Care',
    category: 'Nails',
    description: 'Classic and gel manicures and pedicures with precise shaping and a mirror-smooth finish.',
    image: 'https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&q=80',
    durationMinutes: 45,
    startingPrice: 45,
  },
  {
    id: 'beard-styling',
    name: 'Beard Styling',
    category: 'Hair',
    description: 'A sharp beard trim and shape-up with hot towel finish for a clean, groomed line.',
    image: 'https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&q=80',
    durationMinutes: 30,
    startingPrice: 35,
  },
]
